import Head from 'next/head'
import Image from 'next/image'

//custom components
import Sidebar from "../components/sidebar/Sidebar"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Christian's Portfolio
          
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex ">
        <Sidebar/>
        {/* <div className="w-full flex items-center">
          <div>Content</div>
        </div> */}
      </main>
    </div>
  )
}
